# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xubuntu/CLionProjects/SnapDocLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xubuntu/CLionProjects/SnapDocLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xubuntu/CLionProjects/SnapDocLib/CMakeFiles /home/xubuntu/CLionProjects/SnapDocLib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xubuntu/CLionProjects/SnapDocLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SnapDocLib

# Build rule for target.
SnapDocLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SnapDocLib
.PHONY : SnapDocLib

# fast build rule for target.
SnapDocLib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/build
.PHONY : SnapDocLib/fast

candidate_discoverer.o: candidate_discoverer.cpp.o
.PHONY : candidate_discoverer.o

# target to build an object file
candidate_discoverer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/candidate_discoverer.cpp.o
.PHONY : candidate_discoverer.cpp.o

candidate_discoverer.i: candidate_discoverer.cpp.i
.PHONY : candidate_discoverer.i

# target to preprocess a source file
candidate_discoverer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/candidate_discoverer.cpp.i
.PHONY : candidate_discoverer.cpp.i

candidate_discoverer.s: candidate_discoverer.cpp.s
.PHONY : candidate_discoverer.s

# target to generate assembly for a file
candidate_discoverer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/candidate_discoverer.cpp.s
.PHONY : candidate_discoverer.cpp.s

filters.o: filters.cpp.o
.PHONY : filters.o

# target to build an object file
filters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/filters.cpp.o
.PHONY : filters.cpp.o

filters.i: filters.cpp.i
.PHONY : filters.i

# target to preprocess a source file
filters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/filters.cpp.i
.PHONY : filters.cpp.i

filters.s: filters.cpp.s
.PHONY : filters.s

# target to generate assembly for a file
filters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/filters.cpp.s
.PHONY : filters.cpp.s

helpers.o: helpers.cpp.o
.PHONY : helpers.o

# target to build an object file
helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/helpers.cpp.o
.PHONY : helpers.cpp.o

helpers.i: helpers.cpp.i
.PHONY : helpers.i

# target to preprocess a source file
helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/helpers.cpp.i
.PHONY : helpers.cpp.i

helpers.s: helpers.cpp.s
.PHONY : helpers.s

# target to generate assembly for a file
helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/helpers.cpp.s
.PHONY : helpers.cpp.s

lsd.o: lsd.cpp.o
.PHONY : lsd.o

# target to build an object file
lsd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/lsd.cpp.o
.PHONY : lsd.cpp.o

lsd.i: lsd.cpp.i
.PHONY : lsd.i

# target to preprocess a source file
lsd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/lsd.cpp.i
.PHONY : lsd.cpp.i

lsd.s: lsd.cpp.s
.PHONY : lsd.s

# target to generate assembly for a file
lsd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/lsd.cpp.s
.PHONY : lsd.cpp.s

snap_doc_lib.o: snap_doc_lib.cpp.o
.PHONY : snap_doc_lib.o

# target to build an object file
snap_doc_lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/snap_doc_lib.cpp.o
.PHONY : snap_doc_lib.cpp.o

snap_doc_lib.i: snap_doc_lib.cpp.i
.PHONY : snap_doc_lib.i

# target to preprocess a source file
snap_doc_lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/snap_doc_lib.cpp.i
.PHONY : snap_doc_lib.cpp.i

snap_doc_lib.s: snap_doc_lib.cpp.s
.PHONY : snap_doc_lib.s

# target to generate assembly for a file
snap_doc_lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SnapDocLib.dir/build.make CMakeFiles/SnapDocLib.dir/snap_doc_lib.cpp.s
.PHONY : snap_doc_lib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SnapDocLib"
	@echo "... candidate_discoverer.o"
	@echo "... candidate_discoverer.i"
	@echo "... candidate_discoverer.s"
	@echo "... filters.o"
	@echo "... filters.i"
	@echo "... filters.s"
	@echo "... helpers.o"
	@echo "... helpers.i"
	@echo "... helpers.s"
	@echo "... lsd.o"
	@echo "... lsd.i"
	@echo "... lsd.s"
	@echo "... snap_doc_lib.o"
	@echo "... snap_doc_lib.i"
	@echo "... snap_doc_lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

